version: "3.8"

name: летописи-app

services:
    # Database service
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: databasename
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - "5432:5432"

    # Backend service
    backend:
        build:
            context: ./back
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - database
        environment:
            - DATABASE_URL=postgresql://myuser:mypassword@database:5432/databasename
            - RECOGNITION_MODEL_URL=https://bba1vua4lf4q7qih259e.containers.yandexcloud.net/predict

    # Frontend service
    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - "3001:3000"
        depends_on:
            - backend
        environment:
            - NEXT_PUBLIC_SUPABASE_URL=https://fytsfwgcxtlfjaugtwad.supabase.co
            - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5dHNmd2djeHRsZmphdWd0d2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3MzIzMDYsImV4cCI6MjA0ODMwODMwNn0.NGizuVxMMbbtYMXb-FM_YD4sY4Yoe9XzK6NYp3ify7k
            - NEXT_PUBLIC_BACKEND_API_URL=http://backend:3000
